# Generated by Django 6.0.3 on 2026-05-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_address_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='has_usable_password',
            new_name='has_password_login',
        ),
    ]
