# Generated by Django 6.0.3 on 2026-06-17 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelRegistry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('sasrec', 'SASRec Sequential'), ('bpr', 'BPR Matrix Factorisation'), ('clip', 'CLIP Visual Encoder'), ('reranker', 'Cross-Encoder Reranker')], max_length=20)),
                ('version', models.CharField(max_length=64)),
                ('artifact_path', models.CharField(help_text='Absolute container path or S3 URI to the checkpoint file.', max_length=512)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('metrics', models.JSONField(default=dict, help_text="e.g. {'ndcg@10': 0.42, 'recall@5': 0.31, 'precision@5': 0.28}")),
                ('trained_on_rows', models.PositiveIntegerField(default=0)),
                ('training_duration_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ML Model Registry Entry',
                'verbose_name_plural': 'ML Model Registry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_type', 'is_active'], name='recommendat_model_t_75fb32_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('clip_image', 'CLIP Image Embedding'), ('sbert_text', 'Sentence-BERT Text Embedding'), ('clip_fused', 'CLIP Image + Text Fused')], db_index=True, max_length=20)),
                ('vector', models.JSONField(help_text='Float list — CLIP: 512-d, SBERT: 384-d, fused: 512-d')),
                ('vector_dim', models.PositiveSmallIntegerField()),
                ('model_version', models.CharField(default='v1', help_text='Bumped when embedding model changes, triggers FAISS rebuild.', max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Embedding',
                'verbose_name_plural': 'Product Embeddings',
                'indexes': [models.Index(fields=['source', 'model_version'], name='recommendat_source_c76168_idx')],
                'unique_together': {('product', 'source')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy', models.CharField(choices=[('for_you', 'Personalised For You'), ('similar_items', 'Similar Items (Visual)'), ('trending', 'Trending / Popular'), ('sequential', 'Sequential (SASRec)'), ('hybrid', 'Hybrid Fusion'), ('cold_start', 'Cold-Start Fallback')], db_index=True, max_length=20)),
                ('product_ids', models.JSONField(help_text='Ordered list of product UUID strings, best first.')),
                ('scores', models.JSONField(default=list, help_text='Parallel list of fusion scores for evaluation logging.')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('anchor_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similar_results', to='core.product')),
                ('user', models.ForeignKey(blank=True, help_text='Null for TRENDING / COLD_START strategies.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation Result',
                'indexes': [models.Index(fields=['strategy', 'expires_at'], name='recommendat_strateg_71279e_idx'), models.Index(fields=['user', 'strategy'], name='recommendat_user_id_9da922_idx')],
                'unique_together': {('user', 'anchor_product', 'strategy')},
            },
        ),
    ]
