# Generated by Django 6.0.3 on 2026-06-17 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Anonymous session identifier — matched to user on login.', max_length=64, null=True)),
                ('title', models.CharField(blank=True, help_text='Auto-generated from first user message for display.', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('total_turns', models.PositiveIntegerField(default=0)),
                ('llm_provider', models.CharField(blank=True, help_text='Which LLM provider served this session: groq | openai | ollama', max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, max_length=10)),
                ('content', models.TextField()),
                ('retrieved_chunks', models.JSONField(blank=True, default=list, help_text='List of {text, source, score} dicts used as context.')),
                ('retrieval_scores', models.JSONField(blank=True, default=list, help_text='Parallel list of retrieval relevance scores.')),
                ('referenced_product_ids', models.JSONField(blank=True, default=list, help_text='UUIDs of products mentioned in this response.')),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('faithfulness', models.FloatField(blank=True, null=True)),
                ('answer_relevance', models.FloatField(blank=True, null=True)),
                ('context_precision', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='RAGDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('product_metadata', 'Product Metadata'), ('style_guide', 'Style Guide'), ('faq', 'FAQ / Policy')], db_index=True, max_length=20)),
                ('chunk_index', models.PositiveSmallIntegerField(default=0, help_text='Position of this chunk within its source document.')),
                ('text', models.TextField(help_text='Raw text — used for BM25 retrieval.')),
                ('vector', models.JSONField(blank=True, help_text='Dense embedding vector (list of floats).', null=True)),
                ('vector_dim', models.PositiveSmallIntegerField(default=0)),
                ('embedding_model', models.CharField(default='all-MiniLM-L6-v2', max_length=64)),
                ('is_indexed', models.BooleanField(db_index=True, default=False, help_text='Flipped to True after ChromaDB ingestion.')),
                ('product', models.ForeignKey(blank=True, help_text='Null for FAQ / style guide chunks not tied to a product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_chunks', to='core.product')),
            ],
            options={
                'verbose_name': 'RAG Document Chunk',
                'verbose_name_plural': 'RAG Document Chunks',
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'is_active'], name='chatbot_cha_user_id_9fd70b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_key', 'is_active'], name='chatbot_cha_session_ac9095_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'role'], name='chatbot_cha_session_fb5c97_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chatbot_cha_session_24e989_idx'),
        ),
        migrations.AddIndex(
            model_name='ragdocument',
            index=models.Index(fields=['source_type', 'is_indexed'], name='chatbot_rag_source__ab2133_idx'),
        ),
        migrations.AddIndex(
            model_name='ragdocument',
            index=models.Index(fields=['product', 'source_type'], name='chatbot_rag_product_5e9d3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ragdocument',
            unique_together={('product', 'source_type', 'chunk_index')},
        ),
    ]
