# Generated by Django 6.0.3 on 2026-06-16 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPopularityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(db_index=True, default=0.0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('cart_add_count', models.PositiveIntegerField(default=0)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Popularity Score',
                'ordering': ('-score',),
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=64, null=True)),
                ('query_text', models.TextField()),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('search_bar', 'Search Bar'), ('chatbot', 'Chatbot'), ('visual', 'Visual Search')], default='search_bar', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['query_text'], name='interaction_query_t_0d37ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Anonymous session key — populated before login.', max_length=64, null=True)),
                ('interaction_type', models.CharField(choices=[('view', 'Product View'), ('click', 'Product Click'), ('wishlist', 'Added to Wishlist'), ('cart_add', 'Added to Cart'), ('cart_remove', 'Removed from Cart'), ('purchase', 'Purchased'), ('search', 'Search Query'), ('chat', 'Chatbot Interaction')], db_index=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('weight', models.FloatField(default=1.0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Interaction',
                'verbose_name_plural': 'User Interactions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'interaction_type'], name='interaction_user_id_bf55ae_idx'), models.Index(fields=['user', 'created_at'], name='interaction_user_id_85fac0_idx'), models.Index(fields=['product', 'interaction_type'], name='interaction_product_45bd35_idx'), models.Index(fields=['session_key', 'created_at'], name='interaction_session_320f7c_idx')],
            },
        ),
    ]
